# Generated by Django 5.0.3 on 2024-03-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_user_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Предложение')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.vacancy')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Требование')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.vacancy')),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'Требования',
            },
        ),
    ]
