version: '3'

volumes:
  bot_data:
  static:
  media:

services:
  postgres:
    image: postgres:16.0
    volumes:
      - bot_data:/var/lib/postgresql/data
    user: postgres
    env_file: ../.env
    restart: always

  bot:
    image: zatonskiyfortech/fortech_django_bot:latest
    build: ../fortech_django_bot
    entrypoint: ./bot.sh
    env_file: ../.env
    depends_on:
      - postgres

  admin:
    image: zatonskiyfortech/fortech_django_bot:latest
    build: ../fortech_django_bot
    entrypoint: ./admin.sh
    env_file: ../.env
    volumes:
      - static:/app/static/
    depends_on:
      - postgres

  nginx:
    image: nginx:1.19.3
    ports:
      - "4001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - admin
    restart: always